"""CI workflow template generator.

``socc generate ci`` writes ready-to-use YAML configs that gate every
DTS pull-request through ``socc check``.

Supported platforms: GitHub Actions, GitLab CI.
"""

from __future__ import annotations

_GITHUB_TEMPLATE = """\
# Generated by socc generate ci
# Checks all DTS files in the repo on every push / pull request.
name: socc DTS check

on:
  push:
    paths:
      - '**/*.dts'
  pull_request:
    paths:
      - '**/*.dts'

jobs:
  socc-check:
    name: SoC-Consistency DTS lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install socc
        run: pip install soc-consistency

      - name: Find DTS files and run socc
        run: |
          set +e
          FAILED=0
          while IFS= read -r -d '' dts; do
            echo "--- checking $dts ---"
            socc check "$dts" {soc_flag} {strict_flag} || FAILED=1
          done < <(find . -name '*.dts' -not -path './.git/*' -print0)
          exit $FAILED
"""

_GITLAB_TEMPLATE = """\
# Generated by socc generate ci
socc-check:
  stage: test
  image: python:3.11-slim
  before_script:
    - pip install soc-consistency
  script:
    - |
      FAILED=0
      while IFS= read -r -d '' dts; do
        echo "--- checking $dts ---"
        socc check "$dts" {soc_flag} {strict_flag} || FAILED=1
      done < <(find . -name '*.dts' -not -path './.git/*' -print0)
      exit $FAILED
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH'
      changes:
        - '**/*.dts'
"""


def render_github_actions_workflow(
    *,
    dts_glob: str = "**/*.dts",
    soc_flag: str = "",
    strict_flag: str = "",
) -> str:
    """Return a GitHub Actions workflow YAML string."""
    return _GITHUB_TEMPLATE.format(
        dts_glob=dts_glob,
        soc_flag=soc_flag,
        strict_flag=strict_flag,
    )


def render_gitlab_ci_job(
    *,
    dts_glob: str = "**/*.dts",
    soc_flag: str = "",
    strict_flag: str = "",
) -> str:
    """Return a GitLab CI YAML snippet string."""
    return _GITLAB_TEMPLATE.format(
        dts_glob=dts_glob,
        soc_flag=soc_flag,
        strict_flag=strict_flag,
    )
