"""DTS → human-readable documentation renderer.

``socc generate docs board.dts`` produces a Markdown or HTML document
listing every enabled peripheral with its base address, clocks, voltage
rail, IRQ, and GPIO assignments — suitable for sharing with hardware teams.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

from socc.model.soc import SoC


def render_dts_docs(
    model: SoC,
    *,
    dts_path: str = "",
    soc_name: str = "",
    fmt: str = "markdown",
) -> str:
    """Return a documentation string (Markdown or HTML) for *model*."""
    if fmt == "html":
        return _render_html(model, dts_path=dts_path, soc_name=soc_name)
    return _render_markdown(model, dts_path=dts_path, soc_name=soc_name)


# ── Markdown ──────────────────────────────────────────────────────────────────

def _render_markdown(model: SoC, *, dts_path: str, soc_name: str) -> str:
    lines: list[str] = []
    stem = Path(dts_path).stem if dts_path else "board"
    soc_label = soc_name or model.name or "unknown"

    lines.append(f"# Hardware Documentation — `{stem}`")
    lines.append("")
    lines.append(f"| Field | Value |")
    lines.append(f"|-------|-------|")
    lines.append(f"| DTS file | `{Path(dts_path).name if dts_path else '-'}` |")
    lines.append(f"| SoC | `{soc_label}` |")
    lines.append(f"| Nodes | {len(model.devices)} |")
    lines.append("")

    # Group devices by rough category
    _groups: dict[str, list] = {}
    for name, node in sorted(model.devices.items()):
        compat = str(node.properties.get("compatible", ""))
        category = _categorise(name, compat)
        _groups.setdefault(category, []).append((name, node))

    for category in sorted(_groups.keys()):
        lines.append(f"## {category}")
        lines.append("")
        lines.append("| Node | Compatible | Base Address | IRQ | Notes |")
        lines.append("|------|------------|-------------|-----|-------|")
        for name, node in _groups[category]:
            compat = node.properties.get("compatible", "—")
            reg = node.properties.get("reg", "—")
            base_addr = _extract_first_addr(reg)
            irq = node.properties.get("interrupts", "—")
            irq_str = _summarise_value(irq)
            notes_parts = []
            if node.properties.get("clocks"):
                notes_parts.append("clocks")
            if node.properties.get("iommus"):
                notes_parts.append("iommu")
            if node.properties.get("power-domains"):
                notes_parts.append("power-domain")
            notes = ", ".join(notes_parts) if notes_parts else "—"
            lines.append(
                f"| `{name}` | `{_summarise_value(compat)}` | `{base_addr}` "
                f"| {irq_str} | {notes} |"
            )
        lines.append("")

    # Clock summary
    clocks = getattr(model, "clock_tree", None)
    clocks = getattr(clocks, "clocks", {}) if clocks else {}
    if clocks:
        lines.append("## Clock Summary")
        lines.append("")
        lines.append("| Clock ID | Rate |")
        lines.append("|----------|------|")        
        for clk in sorted(clocks.values(), key=lambda c: c.name):
            rate = f"{clk.rate_hz / 1e6:.1f} MHz" if getattr(clk, "rate_hz", None) else "—"
            lines.append(f"| `{clk.name}` | {rate} |")
        lines.append("")

    # Power domain summary
    power_nodes = getattr(model, "power_tree", None)
    power_nodes = getattr(power_nodes, "nodes", {}) if power_nodes else {}
    if power_nodes:
        lines.append("## Power Domains")
        lines.append("")
        lines.append("| Domain | Voltage |")
        lines.append("|--------|---------|")
        for pd_name, pd in sorted(power_nodes.items()):
            volt = f"{pd.voltage_uv / 1e6:.3f} V" if getattr(pd, "voltage_uv", None) else "—"
            lines.append(f"| `{pd_name}` | {volt} |")

    lines.append("---")
    lines.append("*Generated by [socc](https://github.com/gahingwoo/SoC-Consistency)*")
    return "\n".join(lines) + "\n"


# ── HTML ──────────────────────────────────────────────────────────────────────

def _render_html(model: SoC, *, dts_path: str, soc_name: str) -> str:
    md = _render_markdown(model, dts_path=dts_path, soc_name=soc_name)
    # Minimal HTML wrapper; avoids external dependencies
    stem = Path(dts_path).stem if dts_path else "board"
    # Convert simple Markdown tables / headings to HTML via basic substitution
    rows: list[str] = []
    for line in md.splitlines():
        if line.startswith("# "):
            rows.append(f"<h1>{line[2:]}</h1>")
        elif line.startswith("## "):
            rows.append(f"<h2>{line[3:]}</h2>")
        elif line.startswith("### "):
            rows.append(f"<h3>{line[4:]}</h3>")
        elif line.startswith("---"):
            rows.append("<hr>")
        elif line.startswith("|"):
            rows.append(f'<p class="row">{line}</p>')
        elif line.strip() == "":
            rows.append("")
        else:
            rows.append(f"<p>{line}</p>")
    body = "\n".join(rows)
    return (
        f"<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'>"
        f"<title>{stem} — Hardware Documentation</title>"
        f"<style>body{{font-family:monospace;max-width:1000px;margin:auto;padding:2em}}"
        f"h1,h2{{border-bottom:1px solid #ccc}} "
        f".row{{white-space:pre-wrap}}</style></head>"
        f"<body>{body}</body></html>\n"
    )


# ── helpers ───────────────────────────────────────────────────────────────────

_CATEGORY_MAP = [
    ("uart|serial|console", "Serial / Debug"),
    ("i2c|smbus", "I2C"),
    ("spi|qspi", "SPI"),
    ("usb|xhci|ehci|dwc3", "USB"),
    ("pcie|pci-e", "PCIe"),
    ("gpu|mali|pvr", "GPU"),
    ("vpu|codec|rkvdec|hantro", "Video Codec"),
    ("isp|camera|mipi-csi", "Camera / ISP"),
    ("dsi|display|drm|vop|hdmi|dp", "Display"),
    ("gmac|ethernet|rgmii|sgmii", "Ethernet"),
    ("sdmmc|sdhci|emmc|mmc", "Storage (eMMC/SD)"),
    ("nand|sfc|flash", "Storage (NAND/Flash)"),
    ("iommu|smmu|mmu", "IOMMU"),
    ("thermal|tsadc", "Thermal"),
    ("pwm", "PWM"),
    ("gpio", "GPIO"),
    ("pinctrl|pinmux", "Pin Control"),
    ("clk|cru|cpm", "Clock"),
    ("pmu|power|regulator|supply|ldo|buck|dvs", "Power Management"),
    ("watchdog|wdt", "Watchdog"),
    ("timer|pit|rrtc|rtc", "Timer / RTC"),
    ("dma|dmac", "DMA"),
    ("crypto|rng|trng", "Crypto / Security"),
    ("adc|saradc", "ADC"),
    ("sound|i2s|tdm|audio|codec|dai", "Audio"),
    ("can|canfd", "CAN"),
]


def _categorise(name: str, compat: str) -> str:
    combined = (name + " " + compat).lower()
    for pattern, label in _CATEGORY_MAP:
        import re
        if re.search(pattern, combined):
            return label
    return "Other"


def _extract_first_addr(reg) -> str:
    if not reg or reg == "—":
        return "—"
    s = str(reg).strip()
    # Extract first hex address
    import re
    m = re.search(r"0x[0-9a-fA-F]+", s)
    if m:
        return m.group(0)
    return s[:20]


def _summarise_value(val) -> str:
    if val is None:
        return "—"
    s = str(val)
    if len(s) > 40:
        s = s[:37] + "…"
    return s
