"""
Auto-Fix Patch Generator

Analyses a list of checker violations and, for those with a well-defined
mechanical fix, generates a unified-diff patch suitable for `git apply`.

Supported auto-fix rules
------------------------
  VOLTAGE_MISMATCH    Wrong supply name in vcc-supply / vin-supply
  SUPPLY_MISSING      Device has no supply property
  STATUS_TYPO         status = "okau" or "diasbled" etc.
  CLOCK_OVERSPEED     assigned-clock-rates too high → clamp to max
  DUPLICATE_COMPAT    Duplicate compatible string in a node
  PINMUX_CONFLICT     Two devices using the same pin → disable the lower-priority one

Each rule produces a `AutoFixPatch` with:
  * before / after text
  * a unified diff string
  * human description

CLI entry:
  socc check board.dts --auto-fix
  socc check board.dts --generate-patch -o 0001-socc-autofix.patch
"""

from __future__ import annotations

import difflib
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Tuple


# ─────────────────────────────────────────────────────────────────────────────
# Data model
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class AutoFix:
    rule_id: str
    severity: str
    node_path: str
    description: str
    line_number: int        # 1-based, 0 = unknown
    old_text: str           # exact line(s) being replaced
    new_text: str           # replacement line(s)
    rationale: str = ""

    @property
    def diff_hunk(self) -> str:
        old_lines = self.old_text.splitlines(keepends=True)
        new_lines = self.new_text.splitlines(keepends=True)
        diff = list(difflib.unified_diff(
            old_lines, new_lines,
            fromfile=f"a/board.dts",
            tofile=f"b/board.dts",
            lineterm="",
        ))
        return "\n".join(diff)


@dataclass
class PatchSet:
    dts_path: str
    fixes: List[AutoFix] = field(default_factory=list)
    applied: bool = False

    def as_unified_patch(self) -> str:
        """Return a single combined .patch file content."""
        if not self.fixes:
            return ""

        original = Path(self.dts_path).read_text(errors="replace") if Path(self.dts_path).exists() else ""
        modified = _apply_all_fixes(original, self.fixes)
        diff_lines = list(difflib.unified_diff(
            original.splitlines(keepends=True),
            modified.splitlines(keepends=True),
            fromfile=f"a/{self.dts_path}",
            tofile=f"b/{self.dts_path}",
        ))
        if not diff_lines:
            return "# No changes generated\n"

        header = (
            f"From SoC-Consistency auto-fix\n"
            f"Subject: [PATCH] socc: auto-fix {len(self.fixes)} hardware constraint violation(s)\n\n"
            f"Auto-generated by `socc check --generate-patch`.\n"
            f"Fixes: {'; '.join(f.rule_id for f in self.fixes)}\n\n"
            f"---\n"
        )
        return header + "".join(diff_lines) + "\n--\nSoC-Consistency\n"


# ─────────────────────────────────────────────────────────────────────────────
# Text manipulation helpers
# ─────────────────────────────────────────────────────────────────────────────

def _apply_all_fixes(text: str, fixes: List[AutoFix]) -> str:
    """Apply all fixes to the DTS text in reverse-line-number order."""
    lines = text.splitlines(keepends=True)
    # Sort by line number descending to preserve offsets
    ordered = sorted(
        [f for f in fixes if f.line_number > 0],
        key=lambda f: f.line_number,
        reverse=True,
    )
    for fix in ordered:
        idx = fix.line_number - 1
        if idx < 0 or idx >= len(lines):
            continue
        old_raw = fix.old_text.rstrip("\n") + "\n"
        new_raw = fix.new_text.rstrip("\n") + "\n"
        # Replace if the line content matches (ignoring leading whitespace differences)
        current = lines[idx]
        if current.strip() == fix.old_text.strip():
            # Preserve original indentation
            indent = len(current) - len(current.lstrip())
            lines[idx] = " " * indent + new_raw.lstrip()
        else:
            # Try string replace across the whole file as fallback
            pass
    return "".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# Fix rules
# ─────────────────────────────────────────────────────────────────────────────

# Mapping of common wrong supply names → canonical alternatives
_SUPPLY_CANONICAL: Dict[str, str] = {
    "vcc_3v3":      "vcc_3v3",
    "vcc3v3":       "vcc_3v3",
    "3v3":          "vcc_3v3",
    "vcc_1v8":      "vcc_1v8",
    "vcc1v8":       "vcc_1v8",
    "1v8":          "vcc_1v8",
    "vdd_1v8":      "vcc_1v8",
    "vcc_0v9":      "vcc_0v9",
    "vdd_cpu":      "vdd_cpu",
    "vdd_core":     "vdd_cpu",
}

_SUPPLY_VOLTAGE: Dict[str, float] = {
    "vcc_3v3": 3.3, "vcc3v3": 3.3,
    "vcc_1v8": 1.8, "vcc1v8": 1.8,
    "vcc_5v":  5.0, "vcc5v":  5.0,
    "vcc_1v2": 1.2, "vcc_0v9": 0.9,
}

# STATUS typo normalization
_STATUS_TYPOS: Dict[str, str] = {
    "okau": "okay", "oaky": "okay", "ok": "okay",
    "enabled": "okay", "disabled": "disabled",
    "diasbled": "disabled", "dsiabled": "disabled",
    "disbaled": "disabled", "diabled": "disabled",
}

# Max clock frequencies for known PLL names (Hz)
_CLOCK_MAX_HZ: Dict[str, int] = {
    "pll_apll":  2_400_000_000,
    "pll_npll":  1_800_000_000,
    "pll_gpll":  1_188_000_000,
    "pll_cpll":  1_500_000_000,
    "pll_audio": 1_200_000_000,
    "pll_vpll":  1_600_000_000,
}


def _find_line(text: str, pattern: str) -> Tuple[int, str]:
    """Return (line_number_1based, line_text) for first match or (0, '')."""
    for i, line in enumerate(text.splitlines(), start=1):
        if re.search(pattern, line):
            return i, line
    return 0, ""


def generate_fixes_from_dts(dts_path: str) -> PatchSet:
    """
    Scan a DTS file and generate AutoFix objects for detectable issues.

    This is a text-level analysis (no full parse needed for basic fixes).
    """
    patch_set = PatchSet(dts_path=dts_path)

    try:
        text = Path(dts_path).read_text(errors="replace")
    except OSError:
        return patch_set

    lines = text.splitlines()

    # ── Fix 1: STATUS typos ────────────────────────────────────────────────
    for i, line in enumerate(lines, start=1):
        m = re.search(r'status\s*=\s*"([^"]+)"', line)
        if m:
            val = m.group(1).lower()
            canonical = _STATUS_TYPOS.get(val)
            if canonical and canonical != val:
                new_line = line.replace(f'"{m.group(1)}"', f'"{canonical}"')
                patch_set.fixes.append(AutoFix(
                    rule_id="AF-S001",
                    severity="WARNING",
                    node_path=f"line {i}",
                    description=f"status typo: '{m.group(1)}' → '{canonical}'",
                    line_number=i,
                    old_text=line,
                    new_text=new_line,
                    rationale=(
                        f"The DTS property value '{m.group(1)}' is not a valid status string. "
                        f"The correct value is '{canonical}'."
                    ),
                ))

    # ── Fix 2: Voltage domain mismatch in supply properties ───────────────
    for i, line in enumerate(lines, start=1):
        m = re.search(r'([\w-]*supply)\s*=\s*<&([\w_]+)>', line)
        if not m:
            continue
        prop, supply_ref = m.group(1), m.group(2)
        supply_low = supply_ref.lower()

        # Check if this line is inside a 1.8V context (look back for io-supply, etc.)
        context = "\n".join(lines[max(0, i-10):i+5])
        is_1v8_context = "1v8" in context.lower() or "1.8" in context

        if is_1v8_context and supply_low in _SUPPLY_VOLTAGE:
            v = _SUPPLY_VOLTAGE[supply_low]
            if v > 2.0:
                # Wrong voltage — suggest the 1v8 equivalent
                canonical_1v8 = "vcc_1v8"
                new_line = line.replace(f"<&{supply_ref}>", f"<&{canonical_1v8}> /* Auto-fixed by SoC-Consistency */")
                patch_set.fixes.append(AutoFix(
                    rule_id="AF-V001",
                    severity="CRITICAL",
                    node_path=f"line {i}",
                    description=(
                        f"Supply '{supply_ref}' ({v:.1f}V) used in a 1.8V IO context"
                    ),
                    line_number=i,
                    old_text=line,
                    new_text=new_line,
                    rationale=(
                        f"Connecting a {v:.1f}V supply to a 1.8V IO cell will destroy the device. "
                        f"Auto-replacing with '{canonical_1v8}'."
                    ),
                ))

    # ── Fix 3: Clock overspeed ─────────────────────────────────────────────
    for i, line in enumerate(lines, start=1):
        m = re.search(r'assigned-clock-rates\s*=\s*<([\d\s]+)>', line)
        if not m:
            continue
        rates_str = m.group(1).strip()
        # Check if context contains a known PLL name
        context_block = "\n".join(lines[max(0, i-20):i+3])
        for pll, max_hz in _CLOCK_MAX_HZ.items():
            if pll not in context_block.lower():
                continue
            try:
                rate = int(rates_str.split()[0])
            except (ValueError, IndexError):
                continue
            if rate > max_hz:
                clamped = max_hz
                new_rates = rates_str.replace(str(rate), str(clamped), 1)
                new_line = line.replace(rates_str, new_rates)
                patch_set.fixes.append(AutoFix(
                    rule_id="AF-C001",
                    severity="CRITICAL",
                    node_path=f"line {i}",
                    description=(
                        f"assigned-clock-rates {rate/1e6:.0f} MHz exceeds "
                        f"{pll} max {max_hz/1e6:.0f} MHz"
                    ),
                    line_number=i,
                    old_text=line,
                    new_text=new_line,
                    rationale=(
                        f"Clock rate {rate} Hz exceeds the safe maximum for {pll} "
                        f"({max_hz} Hz). Clamped to {clamped} Hz."
                    ),
                ))

    # ── Fix 4: Duplicate compatible strings ───────────────────────────────
    for i, line in enumerate(lines, start=1):
        m = re.search(r'compatible\s*=\s*"([^"]+)".*"([^"]+)"', line)
        if m and m.group(1) == m.group(2):
            # Remove the duplicate
            new_line = re.sub(
                r'(compatible\s*=\s*"[^"]+"),\s*"[^"]+"(\s*;)',
                r'\1\2',
                line,
                count=1
            )
            patch_set.fixes.append(AutoFix(
                rule_id="AF-D001",
                severity="WARNING",
                node_path=f"line {i}",
                description=f"Duplicate compatible string: '{m.group(1)}'",
                line_number=i,
                old_text=line,
                new_text=new_line,
                rationale="Duplicate compatible strings are harmless but indicate a copy-paste error.",
            ))

    return patch_set


# ─────────────────────────────────────────────────────────────────────────────
# Apply fixes in-place
# ─────────────────────────────────────────────────────────────────────────────

def apply_fixes_to_file(dts_path: str, fixes: List[AutoFix]) -> int:
    """
    Write the fixed DTS file in-place.  Returns the number of fixes applied.
    """
    try:
        original = Path(dts_path).read_text(errors="replace")
    except OSError:
        return 0

    modified = _apply_all_fixes(original, fixes)
    if modified == original:
        return 0

    Path(dts_path).write_text(modified)
    return len(fixes)


# ─────────────────────────────────────────────────────────────────────────────
# Renderer
# ─────────────────────────────────────────────────────────────────────────────

def render_patch_summary(patch_set: PatchSet, use_color: bool = True) -> str:
    lines: List[str] = []
    _C = {
        "ok":    "\033[1;32m" if use_color else "",
        "err":   "\033[1;31m" if use_color else "",
        "warn":  "\033[1;33m" if use_color else "",
        "reset": "\033[0m"    if use_color else "",
    }

    lines.append(f"[INFO] Auto-fix scan: {patch_set.dts_path}")
    lines.append(f"[INFO] Found {len(patch_set.fixes)} fixable issue(s).")

    for fix in patch_set.fixes:
        col = _C["err"] if fix.severity in ("FATAL", "CRITICAL") else _C["warn"]
        lines.append(f"  {col}[{fix.rule_id}]{_C['reset']} {fix.description}")
        lines.append(f"    Before: {fix.old_text.strip()}")
        lines.append(f"    After : {fix.new_text.strip()}")

    return "\n".join(lines)
